### ISSUE TITLE
Improvement of UI 

### ISSUE THREAD

**Issue by basak-rakesh** [SoumyadeepOSD/Dev-for-Society#4]
1.Improvement of Background

**Comment by basak-rakesh** [comment]
@SoumyadeepOSD  I want to work on it. Please assign this issue.

**Comment by SoumyadeepOSD** [comment]
@basak-rakesh  Okay rakesh, new contributors are always welcome. Free free to work on it.

**Comment by SoumyadeepOSD** [comment]
@basak-rakesh  any update?

**Comment by SoumyadeepOSD** [comment]
@basak-rakesh  can I close this issue ?

**Comment by basak-rakesh** [comment]
no. can i get some more time? I can seriously work on this.

**Comment by SoumyadeepOSD** [comment]
@basak-rakesh  Okay I can wait for 1 more week

**Comment by SoumyadeepOSD** [comment]
@basak-rakesh  It seems like you don't want to contribute in this issue. I'm gonna closing it
